name: AWS DEPLOY TO STAGING

#turn off deploy to AWS
on:
  pull_request:
    types: [closed]
    branches:
      - dev

jobs:
  aws-deploy:
    runs-on: windows-latest
    #For google auth
    env:
      APP_ENV: production

    steps:
      - uses: actions/checkout@v3
        # may need to change to version 3
        with:
          ref: dev
      - uses: actions/setup-node@v3
        #May need to change to version 18
        with:
          node-version: 18

      - run: npm install
      - run: npm run build

      - name: Deploy to Server
        uses: garygrossgarten/github-action-scp@release
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY_2 }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "dist/"
          REMOTE_HOST: "ec2-35-90-191-171.us-west-2.compute.amazonaws.com" #Change to aws URL
          REMOTE_USER: ubuntu
          TARGET: "/var/www/html/resume/p2t1"
